server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# This is the address order-service uses to reach catalog-service.
# When we containerize everything in Step 10, this changes to the
# Docker service name instead of localhost.
catalog:
  service:
    url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
