server:
  port: 8083

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5435/analytics_db
    username: analytics_user
    password: analytics_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
